sudo: required #is required to use docker service in travis
services:
  - docker # required, but travis uses older version of docker :(
language: java
dist: trusty
addons:
  sonarqube:
    organization: "dinesh-nadar-github"
    token:
      secure: 3f3c49ac71043de5472e15b18541d725baf201ab
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar