sudo: required #is required to use docker service in travis
services:
  - docker # required, but travis uses older version of docker :(
language: java
dist: trusty
addons:
  sonarqube:
    organization: "dinesh-nadar-github"
    token:
      secure: 3f3c49ac71043de5472e15b18541d725baf201ab
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t sandbox .
  - docker tag sandbox:latest [514752098594].dkr.ecr.us-east-2.amazonaws.com/sandbox:latest
  - docker push [514752098594].dkr.ecr.us-east-2.amazonaws.com/sandbox:latest